#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDOTNET
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="Telefonos")]
	public partial class TelefonosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TelefonosDataContext() : 
				base(global::ProjectDOTNET.Properties.Settings.Default.TelefonosConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public TelefonosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TelefonosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TelefonosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TelefonosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Telefono> Telefonos
		{
			get
			{
				return this.GetTable<Telefono>();
			}
		}
	}
	
	[Table(Name="dbo.Telefonos")]
	public partial class Telefono
	{
		
		private string _Nombre;
		
		private string _Apellidos;
		
		private decimal _DNI;
		
		private string _Handle;
		
		private string _Telefono1;
		
		private string _Image;
		
		public Telefono()
		{
		}
		
		[Column(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[Column(Storage="_Apellidos", DbType="NVarChar(150)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[Column(Storage="_DNI", DbType="Decimal(8,0) NOT NULL")]
		public decimal DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[Column(Storage="_Handle", DbType="NVarChar(50)")]
		public string Handle
		{
			get
			{
				return this._Handle;
			}
			set
			{
				if ((this._Handle != value))
				{
					this._Handle = value;
				}
			}
		}
		
		[Column(Name="Telefono", Storage="_Telefono1", DbType="NVarChar(20)")]
		public string Telefono1
		{
			get
			{
				return this._Telefono1;
			}
			set
			{
				if ((this._Telefono1 != value))
				{
					this._Telefono1 = value;
				}
			}
		}
		
		[Column(Storage="_Image", DbType="NVarChar(100)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
